-- ============================================================
-- SOS - System Obslugi Studenta
-- create-db.sql (HSQLDB - bez DEFAULT values)
-- Plik: src/main/resources/sql/create-db.sql
-- ============================================================

-- Czyszczenie istniejacych tabel (kolejnosc wazna ze wzgledu na FK)
DROP TABLE wypozyczenie_ksiazki IF EXISTS;
DROP TABLE oplata IF EXISTS;
DROP TABLE ocena IF EXISTS;
DROP TABLE plan_zajec IF EXISTS;
DROP TABLE zapis IF EXISTS;
DROP TABLE grupa IF EXISTS;
DROP TABLE przedmiot IF EXISTS;
DROP TABLE student IF EXISTS;

-- Tabela student
CREATE TABLE student (
                         id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         imie             VARCHAR(50)  NOT NULL,
                         nazwisko         VARCHAR(50)  NOT NULL,
                         email            VARCHAR(100) NOT NULL UNIQUE,
                         haslo            VARCHAR(255) NOT NULL,
                         nr_indeksu       VARCHAR(20)  NOT NULL UNIQUE,
                         data_rejestracji DATE
);

-- Tabela przedmiot
CREATE TABLE przedmiot (
                           przedmiot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nazwa        VARCHAR(100) NOT NULL,
                           opis         VARCHAR(500),
                           ects         INTEGER      NOT NULL,
                           prowadzacy   VARCHAR(100)
);

-- Tabela grupa
CREATE TABLE grupa (
                       grupa_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nazwa         VARCHAR(100) NOT NULL,
                       limit_miejsc  INTEGER      NOT NULL,
                       sala          VARCHAR(20),
                       godzina_od    TIME,
                       godzina_do    TIME,
                       przedmiot_id  INTEGER,
                       FOREIGN KEY (przedmiot_id) REFERENCES przedmiot(przedmiot_id)
);

-- Tabela zapis
CREATE TABLE zapis (
                       zapis_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       data_zapisu  DATE,
                       status       VARCHAR(20) NOT NULL,
                       student_id   INTEGER     NOT NULL,
                       grupa_id     INTEGER     NOT NULL,
                       FOREIGN KEY (student_id) REFERENCES student(id),
                       FOREIGN KEY (grupa_id)   REFERENCES grupa(grupa_id)
);

-- Tabela ocena
CREATE TABLE ocena (
                       ocena_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       wartosc          FLOAT   NOT NULL,
                       data_wystawienia DATE,
                       student_id       INTEGER NOT NULL,
                       przedmiot_id     INTEGER NOT NULL,
                       FOREIGN KEY (student_id)   REFERENCES student(id),
                       FOREIGN KEY (przedmiot_id) REFERENCES przedmiot(przedmiot_id)
);

-- Tabela plan_zajec
CREATE TABLE plan_zajec (
                            plan_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            dzien_tygodnia VARCHAR(20) NOT NULL,
                            godzina_od     TIME,
                            godzina_do     TIME,
                            sala           VARCHAR(20),
                            grupa_id       INTEGER     NOT NULL,
                            FOREIGN KEY (grupa_id) REFERENCES grupa(grupa_id)
);

-- Tabela oplata
CREATE TABLE oplata (
                        oplata_id      INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        kwota          DECIMAL(10, 2) NOT NULL,
                        data_platnosci DATE,
                        typ            VARCHAR(50),
                        status         VARCHAR(20)    NOT NULL,
                        student_id     INTEGER        NOT NULL,
                        FOREIGN KEY (student_id) REFERENCES student(id)
);

-- Tabela wypozyczenie_ksiazki
CREATE TABLE wypozyczenie_ksiazki (
                                      wypozyczenie_id   INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      tytul             VARCHAR(200) NOT NULL,
                                      data_wypozyczenia DATE,
                                      data_zwrotu       DATE,
                                      status            VARCHAR(30)  NOT NULL,
                                      student_id        INTEGER      NOT NULL,
                                      FOREIGN KEY (student_id) REFERENCES student(id)
);